# Generated by Django 2.2.4 on 2019-08-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
