# Generated by Django 3.0.6 on 2020-06-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('las_util', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VersionInfo',
            new_name='SectionInfo',
        ),
    ]
